### ISSUE TITLE
Cancel and Skip won't work

### ISSUE THREAD

**Issue by BanuchitraSuruliraj** [QuickBirdEng/SurveyKit#31]
AbortDialogConfiguration is not present in the current version 1.1.0, still, the Cancel button triggers an alert where the actual cancel doesn't navigate to any page but freeze the survey.
The skip button button_skip_question in the footer does not have a text "Skip" set to it. So it just creates a button without text. Only header has a theme set in QuestionView.style().

**Comment by coroutineDispatcher** [comment]
Hello. Thanks for the report. 
There hasn't been a new release yet for Survey kit regarding the dialog. The bug is going to be checked. 
However, if there is something urgent for you, feel free to make a Pull Request and we can check that out :)

**Comment by KlausNie** [comment]
Regarding the cancel: routing after the survey has been canceled or finished is not done by the library. This should be taken care of by the consumer
```kotlin
        surveyView.onSurveyFinish = { taskResult: TaskResult, reason: FinishReason ->
            if (reason == FinishReason.Discarded) {
                // route somewhere else
            }
        }
```

As for the skip text. You are right! I created a PR which should hopefully be merged next week: https://github.com/quickbirdstudios/SurveyKit/pull/36
