### ISSUE TITLE
add customizable "cancel" button

### ISSUE THREAD

**Issue by kspychala-as** [QuickBirdEng/SurveyKit#43]
Hi!
It will be good to have customizable cancel button, because now I can't event change label, so I'm stuck with english "cancel".

Best regards!

**Comment by roedll** [comment]
This should be possible (at least with the current implementation on `master`):

Just override/translate the values originally defined in [/survey/src/main/res/values/strings.xml](https://github.com/quickbirdstudios/SurveyKit/blob/635a40fd785eb14f9c0ca329c15b5c61ce514d79/survey/src/main/res/values/strings.xml#L10) in your own `strings.xml`
