### ISSUE TITLE
"Submit Survey" button not clickable after click one time

### ISSUE THREAD

**Issue by abdlkdrisiktan** [QuickBirdEng/SurveyKit#53]
I finish the survey and clicked the submit survey button after that I tried to click again but button is not clickable. 
All I want to do that I want to click last button many times. I couldn't find how to enable clickable last button.

**Comment by KlausNie** [comment]
If you are referring to the example app (or if you took the code of that one): the last step is not supposed to be doing anything. That would be something that is left to the one using the library

**Comment by razr130** [comment]
So is it possible for the CustomStep to get all the results from all the previous steps without finishing the survey first? 
Like TaskResult in on survey finish. Because I see CustomStep uses StepResult in its parameter which is returning the result from the step itself only

**Comment by KlausNie** [comment]
Oh, you are right! You will not be able to get "all" the results in a step, that is simply not possible.

I'm afraid that is not in the scope of providing intermediate results within the survey to the steps
